ARG IMAGE_FROM
FROM ${IMAGE_FROM}

ARG DEV_USER
ARG INIT_DIR
ARG DEBIAN_FRONTEND=noninteractive

# ----------------------------
# APT packages
# ----------------------------

# Base apt packages
RUN apt-get update && \
    apt-get install -y -qq --no-install-recommends apt-utils locales

# Required apt packages according to https://docs.yoctoproject.org/gatesgarth/ref-manual/ref-system-requirements.html (alphabetically sorted)
RUN apt-get install -y -qq \ 
    build-essential \
    chrpath cpio \
    debianutils diffstat \
    gawk gcc-multilib git \
    iputils-ping \
    libegl1-mesa libsdl1.2-dev \
    mesa-common-dev \
    pylint3 python3 python3-git python3-jinja2 python3-pexpect python3-pip python3-subunit \
    socat \
    texinfo \
    unzip \
    wget \
    xterm xz-utils

# Clean apt caches
RUN apt-get clean && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

# ----------------------------
# System configuration
# ----------------------------

# Set local to en_US.UTF-8 as Yocto requires this
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=en_US.UTF-8
ENV LANG en_US.UTF-8

# Set sh to bash
RUN rm -rf /bin/sh && \
    ln -s /bin/bash /bin/sh

# ----------------------------
# Users and directories
# ----------------------------

# Create and use the same user as in the host system
RUN useradd -G sudo -ms /bin/bash ${DEV_USER}

USER ${DEV_USER}
WORKDIR /home/${DEV_USER}

# ----------------------------
# Environment variables
# ----------------------------
# Support colored command line output
ENV TERM=xterm-256color 

# ----------------------------
# Initialization
# ----------------------------
COPY --chown=${DEV_USER} ${INIT_DIR}/bitbake.sh init.d/bitbake.sh
RUN echo "source ~/init.d/bitbake.sh" >> .bashrc